### ISSUE TITLE
Support conditional sidebar on tabs, not just menu items

### ISSUE THREAD

**Issue by dgrtwo** [ramnathv/shinybones#8]
Right now, conditional sidebars can work only modules inserted at a menu item level, not at a tab level.

**Comment by ramnathv** [comment]
I just committed a change that enables conditional sidebars with tabs. The current implementation ties the sidebar ui to a particular tab. I will export `module_tabs` and `module_tabs_ui` that will make it easier to support conditional sidebars that are common to all tabs on the page. 

Let me know any feedback/comments you have after you try it out!

**Comment by dgrtwo** [comment]
While the sidebar shows up now, I find I'm not able to access any inputs from the sidebar when it's in a tab. I'm guessing this is because it's not choosing the right namespace for the sidebar UI.

Minimal example:

```

test <- function(input, output, session, data_global = list(),
               input_global = list(), ...){
  ns <- session$ns
  
  output$histogram <- renderPlot({
    mtcars %>%
      filter(wt > input$min_weight) %>%
      ggplot(aes(mpg)) +
      geom_histogram()
  })
}


#' @rdname xp
test_ui <- function(id, data_global, ...){
  ns <- shiny::NS(id)
  shiny::fluidRow(
    plotOutput(ns("histogram"))
  )
}

#' @rdname xp
test_ui_sidebar <- function(id, data_global, ...){
  ns <- shiny::NS(id)
  
  sliderInput(ns("min_weight"), "Minimum Weight",
             min = 1, max = 5, value = 3)
}
```

It works fine when `_site.yml` has:

```
  - text: Test
    text: test
    module: test
```

But if it's moved into a tab, the sidebar still shows up but `input$min_weight` is NULL:

```
  - text: Test
    tabs:
      - text: test
        module: test
```

**Comment by ramnathv** [comment]
Thanks for the detailed reprex! It was an issue with the namespace. I just pushed a fix and have tested that your example works. Let me know if it works for you.

**Comment by ramnathv** [comment]
I have confirmed that it works now. Closing this!
