### ISSUE TITLE
Don't try to source README.md files in components/pages folders

### ISSUE THREAD

**Issue by machow** [ramnathv/shinybones#9]
![image](https://user-images.githubusercontent.com/2574498/55104880-a2a21a00-50a1-11e9-8a5d-dd6d5e119e24.png)

AFAICT the source_dirs function would just need to filter for R source files...

```
> source_dirs
function (...) 
{
    list(...) %>% purrr::walk(~{
        dir(.x, full.names = TRUE) %>% purrr::walk(source)
    })
}
```

**Comment by ramnathv** [comment]
@machow Use `shinybones::source_dirs` so it sources only the R files. I had a version of this function in `dcdash` that needs to be removed to prevent the namespace conflict, that is causing this behavior.

**Comment by machow** [comment]
@ramnathv thanks!
